// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrailLoaded.Models;

public partial class ContactForm
{
    public int ContactId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Subject { get; set; }

    public string Message { get; set; }

    public string PreferredContactMethod { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool? IsResolved { get; set; }
}