// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrailLoaded.Models;

public partial class NewAdmission
{
    public int AdmissionId { get; set; }

    public string AdmissionCode { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Gender { get; set; }

    public DateOnly DateOfBirth { get; set; }

    public string Standard { get; set; }

    public string Course { get; set; }

    public string StudentPhone { get; set; }

    public string Email { get; set; }

    public string StudentAadhaar { get; set; }

    public string FatherName { get; set; }

    public string MotherName { get; set; }

    public string ParentMobile { get; set; }

    public string FatherOccupation { get; set; }

    public string ParentAadhaar { get; set; }

    public string Address { get; set; }

    public DateTime? AdmissionDate { get; set; }
}