// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TrailLoaded.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public int AdmissionId { get; set; }

    public bool? AdmFeePaid { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual NewAdmission Admission { get; set; }
}